In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [5]:
url="https://www.premierleague.com/stats/top/players/goals"
r=requests.get(url)
print(r)

<Response [200]>

In [6]:
soup=BeautifulSoup(r.text,"lxml")
#print(soup)

In [7]:
name=soup.find_all("a",class_="playerName")
#print(name.text)
ply_name=[]
for i in name:
    name=i.text.strip()
    ply_name.append(name)
print(ply_name)

['Erling Haaland', 'Cole Palmer', 'Alexander Isak', 'Phil Foden', 'Dominic Solanke', 'Ollie Watkins', 'Mohamed Salah', 'Son Heung-Min', 'Jarrod Bowen', 'Jean-Philippe Mateta']

In [8]:

clb=soup.find_all("a",class_="stats-table__cell-icon-align")
#print(name.text)
club_name=[]
for i in clb:
    clb=i.text.strip()
    club_name.append(clb)
print(club_name)

['Manchester City', 'Chelsea', 'Newcastle United', 'Manchester City', 'Bournemouth', 'Aston Villa', 'Liverpool', 'Tottenham Hotspur', 'West Ham United', 'Crystal Palace']

In [9]:


nation=soup.find_all("div",class_="stats-table__cell-icon-align")
#print(name.text)
na_name=[]
for i in nation:
    nation=i.text.strip()
    na_name.append(nation)
print(na_name)

['Norway', 'England', 'Sweden', 'England', 'England', 'England', 'Egypt', 'South Korea', 'England', 'France']

In [10]:
ast=soup.find_all("td",class_="stats-table__main-stat")
#print(name.text)
ast_name=[]
for i in ast:
    ast=i.text.strip()
    ast_name.append(ast)
print(ast_name)

['27', '22', '21', '19', '19', '19', '18', '17', '16', '16']

In [11]:

assist=pd.DataFrame({"palyer name":ply_name,"club":club_name,"nationality":na_name,"assists":ast_name})
assist

            palyer name               club  nationality assists
0        Erling Haaland    Manchester City       Norway      27
1           Cole Palmer            Chelsea      England      22
2        Alexander Isak   Newcastle United       Sweden      21
3            Phil Foden    Manchester City      England      19
4       Dominic Solanke        Bournemouth      England      19
5         Ollie Watkins        Aston Villa      England      19
6         Mohamed Salah          Liverpool        Egypt      18
7         Son Heung-Min  Tottenham Hotspur  South Korea      17
8          Jarrod Bowen    West Ham United      England      16
9  Jean-Philippe Mateta     Crystal Palace       France      16

In [9]:
assist.to_csv('new.pl_most.assists.csv')

# top goal scorer

In [10]:
url="https://www.premierleague.com/stats/top/players/goals"
r=requests.get(url)
print(r)

<Response [200]>

In [11]:
soup=BeautifulSoup(r.text,"lxml")
#print(soup)
name=soup.find_all("a",class_="playerName")
#print(name.text)
ply_name=[]
for i in name:
    name=i.text.strip()
    ply_name.append(name)
print(ply_name)

['Erling Haaland', 'Mohamed Salah', 'Dominic Solanke', 'Son Heung-Min', 'Jarrod Bowen', 'Ollie Watkins', 'Richarlison', 'Hwang Hee-Chan', 'Alexander Isak', 'Cole Palmer']

In [12]:

clb=soup.find_all("a",class_="stats-table__cell-icon-align")
#print(name.text)
club_name=[]
for i in clb:
    clb=i.text.strip()
    club_name.append(clb)
print(club_name)

['Manchester City', 'Liverpool', 'Bournemouth', 'Tottenham Hotspur', 'West Ham United', 'Aston Villa', 'Tottenham Hotspur', 'Wolverhampton Wanderers', 'Newcastle United', 'Chelsea']

In [13]:

nation=soup.find_all("div",class_="stats-table__cell-icon-align")
#print(name.text)
na_name=[]
for i in nation:
    nation=i.text.strip()
    na_name.append(nation)
print(na_name)

['Norway', 'Egypt', 'England', 'South Korea', 'England', 'England', 'Brazil', 'South Korea', 'Sweden', 'England']

In [14]:
goal=soup.find_all("td",class_="stats-table__main-stat")
#print(name.text)
goals=[]
for i in goal:
    goal=i.text.strip()
    goals.append(goal)
print(goals)

['16', '14', '13', '12', '11', '11', '10', '10', '10', '10']

In [22]:

goal=pd.DataFrame({"palyer name":ply_name,"club":club_name,"nationality":na_name,"goal":goals})
goal

       palyer name                     club  nationality goal
0   Erling Haaland          Manchester City       Norway   16
1    Mohamed Salah                Liverpool        Egypt   14
2  Dominic Solanke              Bournemouth      England   13
3    Son Heung-Min        Tottenham Hotspur  South Korea   12
4     Jarrod Bowen          West Ham United      England   11
5    Ollie Watkins              Aston Villa      England   11
6      Richarlison        Tottenham Hotspur       Brazil   10
7   Hwang Hee-Chan  Wolverhampton Wanderers  South Korea   10
8   Alexander Isak         Newcastle United       Sweden   10
9      Cole Palmer                  Chelsea      England   10

In [23]:
goal.to_csv('new.pl_most.goal.csv')

# most clean sheet

In [24]:
url="https://www.premierleague.com/stats/top/players/clean_sheet"
r=requests.get(url)
print(r)

<Response [200]>

In [25]:
soup=BeautifulSoup(r.text,"lxml")
#print(soup)
name=soup.find_all("a",class_="playerName")
#print(name.text)
ply_name=[]
for i in name:
    name=i.text.strip()
    ply_name.append(name)
print(ply_name)

clb=soup.find_all("a",class_="stats-table__cell-icon-align")
#print(name.text)
club_name=[]
for i in clb:
    clb=i.text.strip()
    club_name.append(clb)
print(club_name)

nation=soup.find_all("div",class_="stats-table__cell-icon-align")
#print(name.text)
na_name=[]
for i in nation:
    nation=i.text.strip()
    na_name.append(nation)
print(na_name)

goal=soup.find_all("td",class_="stats-table__main-stat")
#print(name.text)
goals=[]
for i in goal:
    goal=i.text.strip()
    goals.append(goal)
print(goals)

['William Saliba', 'Jordan Pickford', 'James Tarkowski', 'Alisson Becker', 'Jarrad Branthwaite', 'James Garner', 'Dwight McNeil', 'Vitalii Mykolenko', 'André Onana', 'David Raya']
['Arsenal', 'Everton', 'Everton', 'Liverpool', 'Everton', 'Everton', 'Everton', 'Everton', 'Manchester United', 'Arsenal']
['France', 'England', 'England', 'Brazil', 'England', 'England', 'England', 'Ukraine', 'Cameroon', 'Spain']
['9', '8', '8', '7', '7', '7', '7', '7', '7', '7']

In [26]:

clen=pd.DataFrame({"palyer name":ply_name,"club":club_name,"nationality":na_name,"clean Sheet":goals})
clen

          palyer name               club nationality clean Sheet
0      William Saliba            Arsenal      France           9
1     Jordan Pickford            Everton     England           8
2     James Tarkowski            Everton     England           8
3      Alisson Becker          Liverpool      Brazil           7
4  Jarrad Branthwaite            Everton     England           7
5        James Garner            Everton     England           7
6       Dwight McNeil            Everton     England           7
7   Vitalii Mykolenko            Everton     Ukraine           7
8         André Onana  Manchester United    Cameroon           7
9          David Raya            Arsenal       Spain           7

In [27]:
clen.to_csv('new.pl_most.clean_sheet.csv')